import Doc1 from '/public/images/doctors/balakrishna shetty.jpg'
export const doctors = [
    // Diabetes Specialists
    {
      id: 1,
      name: "Dr. Balakrishna Shetty",
      specialty: "Diabetes Specialist",
      location: "Koramangala, Bangalore",
      consultationFee: 600,
      modeOfConsultation: "Online/Clinic",
      imageUrl: Doc1,
      experience: "10 years",
      languages: ["English", "Kannada", "Hindi"],
      availability: "9 AM - 5 PM",
    },
    {
      id: 2,
      name: "Dr. Ananya Rao",
      specialty: "Diabetes Specialist",
      location: "Indiranagar, Bangalore",
      consultationFee: 550,
      modeOfConsultation: "Clinic",
      imageUrl: Doc1,
      experience: "12 years",
      languages: ["English", "Kannada"],
      availability: "10 AM - 6 PM",
    },
    {
      id: 3,
      name: "Dr. Prakash Naik",
      specialty: "Diabetes Specialist",
      location: "Whitefield, Bangalore",
      consultationFee: 700,
      modeOfConsultation: "Online",
      imageUrl: Doc1,
      experience: "15 years",
      languages: ["English", "Hindi"],
      availability: "8 AM - 2 PM",
    },
  
    // Heart Specialists
    {
      id: 4,
      name: "Dr. Jane Smith",
      specialty: "Heart Treatment",
      location: "HSR Layout, Bangalore",
      consultationFee: 900,
      modeOfConsultation: "Clinic",
      imageUrl: Doc1,
      experience: "18 years",
      languages: ["English", "Kannada"],
      availability: "9 AM - 1 PM",
    },
    {
      id: 5,
      name: "Dr. Rajeev Kumar",
      specialty: "Heart Treatment",
      location: "Jayanagar, Bangalore",
      consultationFee: 800,
      modeOfConsultation: "Online/Clinic",
      imageUrl: Doc1,
      experience: "10 years",
      languages: ["English", "Hindi", "Kannada"],
      availability: "11 AM - 7 PM",
    },
    {
      id: 6,
      name: "Dr. Neha Sharma",
      specialty: "Heart Treatment",
      location: "Bellandur, Bangalore",
      consultationFee: 750,
      modeOfConsultation: "Online",
      imageUrl: Doc1,
      experience: "8 years",
      languages: ["English", "Kannada"],
      availability: "1 PM - 9 PM",
    },
  
    // Asthma Specialists
    {
      id: 7,
      name: "Dr. Sam Wilson",
      specialty: "Asthma Specialist",
      location: "Marathahalli, Bangalore",
      consultationFee: 650,
      modeOfConsultation: "Clinic",
      imageUrl: Doc1,
      experience: "10 years",
      languages: ["English", "Hindi"],
      availability: "8 AM - 4 PM",
    },
    {
      id: 8,
      name: "Dr. Anita Das",
      specialty: "Asthma Specialist",
      location: "Yelahanka, Bangalore",
      consultationFee: 700,
      modeOfConsultation: "Online",
      imageUrl: Doc1,
      experience: "12 years",
      languages: ["English", "Kannada", "Bengali"],
      availability: "10 AM - 5 PM",
    },
    {
      id: 9,
      name: "Dr. Kiran Reddy",
      specialty: "Asthma Specialist",
      location: "BTM Layout, Bangalore",
      consultationFee: 600,
      modeOfConsultation: "Online/Clinic",
      imageUrl: Doc1,
      experience: "7 years",
      languages: ["English", "Telugu", "Kannada"],
      availability: "9 AM - 3 PM",
    },
  
    // Skin Issues Specialists
    {
      id: 10,
      name: "Dr. Alice Green",
      specialty: "Skin Issues Specialist",
      location: "Electronic City, Bangalore",
      consultationFee: 500,
      modeOfConsultation: "Clinic",
      imageUrl: Doc1,
      experience: "6 years",
      languages: ["English", "Hindi"],
      availability: "8 AM - 2 PM",
    },
    {
      id: 11,
      name: "Dr. Rachna Tiwari",
      specialty: "Skin Issues Specialist",
      location: "Banashankari, Bangalore",
      consultationFee: 550,
      modeOfConsultation: "Online/Clinic",
      imageUrl: Doc1,
      experience: "8 years",
      languages: ["English", "Kannada"],
      availability: "10 AM - 4 PM",
    },
    {
      id: 12,
      name: "Dr. Mahesh Patil",
      specialty: "Skin Issues Specialist",
      location: "Hebbal, Bangalore",
      consultationFee: 600,
      modeOfConsultation: "Online",
      imageUrl: Doc1,
      experience: "10 years",
      languages: ["English", "Marathi", "Kannada"],
      availability: "9 AM - 5 PM",
    },
  
    // Cancer Specialists
    {
      id: 13,
      name: "Dr. Robert Brown",
      specialty: "Cancer Specialist",
      location: "Malleshwaram, Bangalore",
      consultationFee: 1500,
      modeOfConsultation: "Clinic",
      imageUrl: Doc1,
      experience: "20 years",
      languages: ["English", "Kannada"],
      availability: "10 AM - 4 PM",
    },
    {
      id: 14,
      name: "Dr. Sunita Kapoor",
      specialty: "Cancer Specialist",
      location: "Vijayanagar, Bangalore",
      consultationFee: 1200,
      modeOfConsultation: "Online",
      imageUrl: Doc1,
      experience: "18 years",
      languages: ["English", "Hindi"],
      availability: "11 AM - 6 PM",
    },
    {
      id: 15,
      name: "Dr. Aman Joshi",
      specialty: "Cancer Specialist",
      location: "Ulsoor, Bangalore",
      consultationFee: 1000,
      modeOfConsultation: "Online/Clinic",
      imageUrl: Doc1,
      experience: "16 years",
      languages: ["English", "Kannada", "Gujarati"],
      availability: "9 AM - 3 PM",
    },
  
    // More Specialists for Variety
    {
      id: 16,
      name: "Dr. Meena Nair",
      specialty: "Diabetes Specialist",
      location: "RT Nagar, Bangalore",
      consultationFee: 650,
      modeOfConsultation: "Online",
      imageUrl: Doc1,
      experience: "9 years",
      languages: ["English", "Malayalam", "Kannada"],
      availability: "8 AM - 2 PM",
    },
    {
      id: 17,
      name: "Dr. Varun Shetty",
      specialty: "Heart Treatment",
      location: "Basavanagudi, Bangalore",
      consultationFee: 850,
      modeOfConsultation: "Clinic",
      imageUrl: Doc1,
      experience: "11 years",
      languages: ["English", "Kannada"],
      availability: "1 PM - 7 PM",
    },
    {
      id: 18,
      name: "Dr. Lakshmi Iyer",
      specialty: "Asthma Specialist",
      location: "Hennur, Bangalore",
      consultationFee: 500,
      modeOfConsultation: "Online",
      imageUrl: Doc1,
      experience: "6 years",
      languages: ["English", "Kannada", "Tamil"],
      availability: "10 AM - 4 PM",
    },
    {
      id: 19,
      name: "Dr. Mohan Kulkarni",
      specialty: "Skin Issues Specialist",
      location: "Rajajinagar, Bangalore",
      consultationFee: 550,
      modeOfConsultation: "Clinic",
      imageUrl: Doc1,
      experience: "12 years",
      languages: ["English", "Kannada"],
      availability: "9 AM - 1 PM",
    },
    {
      id: 20,
      name: "Dr. Sanjay Verma",
      specialty: "Cancer Specialist",
      location: "Kalyan Nagar, Bangalore",
      consultationFee: 1400,
      modeOfConsultation: "Online/Clinic",
      imageUrl: Doc1,
      experience: "15 years",
      languages: ["English", "Kannada", "Hindi"],
      availability: "8 AM - 12 PM",
    },
  ];
  